version: "3.7"

services:
  openresty:
    image: openresty/openresty:1.21.4.1rc3-bionic
    container_name: op-dev
    restart: always
    ports:
      - "10086:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/usr/local/openresty/nginx/logs
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/local/openresty/nginx/app
